platform :ios, '12.0'

target 'The Banana Tap Challenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Calometer
	pod 'Alamofire'
end

